=== begotrujano/ordinario-ftw/data/videojuegos.dtd
<!ELEMENT catalogo (videojuego+)>
<!ELEMENT videojuego (titulo, genero, precio, imagen, plataformas)>
<!ATTLIST videojuego id ID #REQUIRED>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT genero (#PCDATA)>
<!ELEMENT precio (#PCDATA)>
<!ELEMENT imagen (#PCDATA)>
<!ELEMENT plataformas (#PCDATA)>

=== begotrujano/ordinario-ftw/data/videojuegos.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE catalogo SYSTEM "videojuegos.dtd">
<catalogo>
    <videojuego id="v1">
        <titulo>Cyberpunk 2077</titulo>
        <genero>RPG</genero>
        <precio>899.00</precio>
        <imagen>https://image.api.playstation.com/vulcan/ap/rnd/202008/0416/6Bo40lnWU0BhgrOUm7Cb6by3.png</imagen>
        <plataformas>PC, PS5, Xbox</plataformas>
    </videojuego>
    <videojuego id="v2">
        <titulo>LEGO Batman: El Legado del Caballero Oscuro</titulo>
        <genero>Aventura</genero>
        <precio>1199.00</precio>
        <imagen>https://image.api.playstation.com/vulcan/ap/rnd/202508/1316/3302f35b66691aa405aee31624c0c95fe73081be8e0c75bb.png</imagen>
        <plataformas>PC, PS5, Xbox</plataformas>
    </videojuego>
    <videojuego id="v3">
        <titulo>Elden Ring</titulo>
        <genero>RPG</genero>
        <precio>1200.00</precio>
        <imagen>https://i.redd.it/bueqtztxmnj81.png</imagen>
        <plataformas>PC, PS5</plataformas>
    </videojuego>
    
</catalogo>
